version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:16.0.1
        auth:
          username: $DOCKERHUB_ID
          password: $DOCKERHUB_PASS
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}